twig:
    default_path: '%kernel.project_dir%/templates'

knp_paginator:
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'

when@test:
    twig:
        strict_variables: true
